name: deploy_frontend

on:
  push:
    branches:
      - deploy

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with SSH Key
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_SE }} # ใช้ SSH Key ชื่อ SE
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          file: frontend/Dockerfile
          context: frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cyberkub-frontend:latest
